=== serenaliaojc/HTTP-5203-XML/ass2/tickets.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="tickets">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ticket" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:dateTime" name="submitdate"/>
              <xs:element type="xs:string" name="category"/>
              <xs:element name="user">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="id"/>
                    <xs:element type="xs:string" name="username"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="description"/>
              <xs:element name="messages" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="message" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="content"/>
                          <xs:element name="assignedstaff">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="id"/>
                                <xs:element type="xs:string" name="firstname"/>
                                <xs:element type="xs:string" name="lastname"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="required"/>
            <xs:attribute type="xs:string" name="status" use="required"/>
            <xs:attribute type="xs:string" name="priority" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== serenaliaojc/HTTP-5203-XML/ass2/tickets.xml
<?xml version="1.0" encoding="utf-8"?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tickets.xsd">
	<ticket id="1" status="pending" priority="high">
		<submitdate>2018-01-30T09:08:19</submitdate>
		<category>Technical</category>
		<user>
			<id>u0034</id>
			<username>happytreefriend</username>
		</user>
		<description>PHPadmin error</description>
	</ticket>
	<ticket id="2" status="closed" priority="medium">
		<submitdate>2018-02-01T17:25:01</submitdate>
		<category>Complaint</category>
		<user>
			<id>u0001</id>
			<username>user1.0.2</username>
		</user>
		<description>The man in the front desk needs to relearn his manner.</description>
		<messages>
			<message>
				<content>Lorem ipsum dolor sit amet.</content>
				<assignedstaff>
					<id>s0004</id>
					<firstname>Jessie</firstname>
					<lastname>Drew</lastname>
				</assignedstaff>
			</message>
			<message>
				<content>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, repudiandae.</content>
				<assignedstaff>
					<id>s0010</id>
					<firstname>Conner</firstname>
					<lastname>Kent</lastname>
				</assignedstaff>
			</message>
		</messages>
	</ticket>
	<ticket id="3" status="assigned" priority="low">
		<submitdate>2018-02-05T20:01:49</submitdate>
		<category>Inquire</category>
		<user>
			<id>u0202</id>
			<username>HelloMegan</username>
		</user>
		<description>Where can I check my subscriptions?</description>
		<messages>
			<message>
				<content>Lorem ipsum dolor sit amet, consectetur.</content>
				<assignedstaff>
					<id>s0010</id>
					<firstname>Conner</firstname>
					<lastname>Kent</lastname>
				</assignedstaff>
			</message>
		</messages>
	</ticket>
<ticket id="4" status="closed" priority="low"><submitdate>2018-03-28T04:37:06</submitdate><category>Inquire</category><user><id>u0202</id><username>HelloMegan</username></user><description>Is this ticket system working?</description><messages><message><content>Yes, I think it's working :)</content><assignedstaff><id>s0010</id><firstname>Conner</firstname><lastname>Kent</lastname></assignedstaff></message></messages></ticket></tickets>
