=== serenaliaojc/HTTP-5203-XML/ass2/users.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="users">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="user" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="username"/>
                    <xs:element type="xs:string" name="firstname"/>
                    <xs:element type="xs:string" name="middlename" minOccurs="0"/>
                    <xs:element type="xs:string" name="lastname"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:dateTime" name="firstlogindate"/>
              <xs:element type="xs:dateTime" name="lastlogindate"/>
              <xs:element type="xs:string" name="email"/>
              <xs:element type="xs:anyURI" name="avatar"/>
              <xs:element type="xs:string" name="password"/>
            </xs:sequence>
            <xs:attribute name="id" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[a-z][0-9]{4}"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="type" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="client|admin"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== serenaliaojc/HTTP-5203-XML/ass2/users.xml
<?xml version="1.0" encoding="utf-8" ?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
	<user id="u0034" type="client">
		<name>
			<username>happytreefriend</username>
			<firstname>Jane</firstname>
			<lastname>Crock</lastname>
		</name>
		<firstlogindate>2017-11-10T09:07:29</firstlogindate>
		<lastlogindate>2018-01-30T19:08:19</lastlogindate>
		<email>happytreefriend@gmail.com</email>
		<avatar>avatar-random.jpg</avatar>
		<password>password</password>
	</user>
	<user id="u0202" type="client">
		<name>
			<username>HelloMegan</username>
			<firstname>Megan</firstname>
			<middlename>Mars</middlename>
			<lastname>Anderson</lastname>
		</name>
		<firstlogindate>2017-12-14T18:10:07</firstlogindate>
		<lastlogindate>2018-02-11T09:18:15</lastlogindate>
		<email>hellomegan@hotmail.com</email>
		<avatar>hellomegan-photo.png</avatar>
		<password>password</password>
	</user>
	<user id="s0010" type="admin">
		<name>
			<username>admin</username>
			<firstname>Conner</firstname>
			<lastname>Kent</lastname>
		</name>
		<firstlogindate>2014-01-14T08:00:00</firstlogindate>
		<lastlogindate>2018-02-12T19:18:09</lastlogindate>
		<email>admin@supporttickets.com</email>
		<avatar>admin.jpg</avatar>
		<password>admin</password>
	</user>
</users>
